name: release command
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - name: Run test in Staging
        run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy.sh kazuo_ikeda
      - name: Deploy to Production, if the test is successful, deploy to Production
        run: echo "Deploy step succeeded!"
        if: ${{ success() }}
      - name: Handle failure
        run: echo "test failed!"
        if: ${{ failure() }}
